### PR TITLE
Resolves #285 - show quoted notes on feeds

### LINKED ISSUE #285: Show different kind of quotes
Hi,

On Plasma feed I see that many kind of quotes are showed. Please add support to it:

photo_4900207035472259888_y

### PR DESCRIPTION
**Pull request by jmateoac**
https://github.com/plasma-social/plasma/assets/108030953/bbc1d771-2088-4347-82eb-7ea41d04ee0d

### CODE REVIEW

**Comment by jmateoac** [comment]
Current dependencies on/for this PR:
* main
  * **PR #287** <a href="https://app.graphite.dev/github/pr/plasma-social/plasma/287" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/plasma-social/plasma/287?utm_source=stack-comment).

**Comment by bitcoinuser** [comment]
Great. Will quotes from highlighter.com and Habla.News appear too? Thanks.

**Comment by jmateoac** [comment]
> Habla.News appear too? Thanks.

Not sure, but I can add another ticket for that. Where can I see an example of those quotes?

**Comment by bitcoinuser** [comment]
> > Habla.News appear too? Thanks.
> 
> Not sure, but I can add another ticket for that. Where can I see an example of those quotes?

Here is an example: 

nostr:nevent1qqs8qtkg4dl6t0ltqftnq8nka84fpuaruh9z25vqx3geffhz0nuhzygpzfmhxue69uhk7enxvd5xz6tw9ec82cszyzfar05tyqxe23krrfclwl40t6e4z6jgfqnrd7jslxdk66nq8ln86qcyqqqqqqg85f99z

**Comment by bitcoinuser** [comment]
> > > Habla.News appear too? Thanks.
> > 
> > 
> > Not sure, but I can add another ticket for that. Where can I see an example of those quotes?
> 
> Here is an example:
> 
> nostr:nevent1qqs8qtkg4dl6t0ltqftnq8nka84fpuaruh9z25vqx3geffhz0nuhzygpzfmhxue69uhk7enxvd5xz6tw9ec82cszyzfar05tyqxe23krrfclwl40t6e4z6jgfqnrd7jslxdk66nq8ln86qcyqqqqqqg85f99z

On amethyst:

Screenshot_2023-06-08-19-07-54-818_com vitorpamplona amethyst

**Comment by bitcoinuser** [comment]
And please a new version today, haha. Thanks

**Pull request merged**
